
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustify-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustify-test
  template:
    metadata:
      labels:
        app: rustify-test
    spec:
      containers:
      - name: test-container
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
    