name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: rustify
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: rustify
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_name: rustify

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Package Binary
      run: |
        cd target/${{ matrix.target }}/release
        tar czf ../../../rustify-${{ matrix.target }}.tar.gz ${{ matrix.binary_name }}
        
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: rustify-${{ matrix.target }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 