name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: false
          - os: macos-latest
            target: x86_64-apple-darwin
            cross: false
          - os: macos-latest
            target: aarch64-apple-darwin
            cross: true

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install openssl@3
        echo 'export OPENSSL_DIR=$(brew --prefix openssl@3)' >> $GITHUB_ENV
        echo 'export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@3)/include' >> $GITHUB_ENV
        echo 'export OPENSSL_LIB_DIR=$(brew --prefix openssl@3)/lib' >> $GITHUB_ENV
        
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Install cross-compilation tools
      if: matrix.cross
      run: |
        rustup target add ${{ matrix.target }}
        
    - name: Build
      env:
        OPENSSL_DIR: ${{ env.OPENSSL_DIR }}
        OPENSSL_INCLUDE_DIR: ${{ env.OPENSSL_INCLUDE_DIR }}
        OPENSSL_LIB_DIR: ${{ env.OPENSSL_LIB_DIR }}
        MACOSX_DEPLOYMENT_TARGET: '10.15'
      run: |
        cargo build --release --target ${{ matrix.target }}
        
    - name: Prepare binary
      run: |
        cd target/${{ matrix.target }}/release
        chmod +x rustify
        tar czf ../../../rustify-${{ matrix.target }}.tar.gz rustify
      
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: rustify-${{ matrix.target }}.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}